// ==============================================================================
// HIPOTECALY AI: Configuración Definitiva de los 20 Portales Locales Uruguayos (Fase0)
// Configuración declarativa pura con ingestion_enabled = false y sin crawlers
// ==============================================================================

import { PropertySource } from '../types/aiAppraisalFase0';

export interface PortalSourceSeed extends Omit<PropertySource, 'id' | 'createdAt' | 'updatedAt'> {
  id?: string;
  category: 'portales_lideres_uy' | 'cadenas_inmobiliarias_uy' | 'operadores_locales_uy';
}

export const TOP_20_PORTALS_CONFIG: PortalSourceSeed[] = [
  {
    code: 'mercadolibre_uy',
    name: 'Mercado Libre Inmuebles',
    domain: 'inmuebles.mercadolibre.com.uy',
    countryCode: 'UY',
    sourceType: 'portal',
    baseUrl: 'https://inmuebles.mercadolibre.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false, // Ingesta desactivada en Fase 0
    priority: 1,
    trustLevel: 1.0,
    rateLimitPerMinute: 60,
    category: 'portales_lideres_uy',
    notes: 'Portal líder generalista en Uruguay',
  },
  {
    code: 'infocasas',
    name: 'InfoCasas',
    domain: 'infocasas.com.uy',
    countryCode: 'UY',
    sourceType: 'portal',
    baseUrl: 'https://www.infocasas.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 2,
    trustLevel: 1.0,
    rateLimitPerMinute: 60,
    category: 'portales_lideres_uy',
    notes: 'Portal especializado en residencial y desarrollos UY',
  },
  {
    code: 'gallito_uy',
    name: 'Gallito Luis',
    domain: 'gallito.com.uy',
    countryCode: 'UY',
    sourceType: 'portal',
    baseUrl: 'https://www.gallito.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 3,
    trustLevel: 0.9,
    rateLimitPerMinute: 30,
    category: 'portales_lideres_uy',
    notes: 'Clasificado tradicional uruguayo',
  },
  {
    code: 'remax_uy',
    name: 'RE/MAX Uruguay',
    domain: 'remax.com.uy',
    countryCode: 'UY',
    sourceType: 'franquicia',
    baseUrl: 'https://www.remax.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 4,
    trustLevel: 0.95,
    rateLimitPerMinute: 40,
    category: 'cadenas_inmobiliarias_uy',
    notes: 'Red inmobiliaria de franquicias en Uruguay',
  },
  {
    code: 'engel_volkers_uy',
    name: 'Engel & Völkers Uruguay',
    domain: 'engelvoelkers.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.engelvoelkers.com/uruguay',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 5,
    trustLevel: 0.95,
    rateLimitPerMinute: 20,
    category: 'cadenas_inmobiliarias_uy',
    notes: 'Inmobiliaria de segmento residencial alto',
  },
  {
    code: 'sothebys_uy',
    name: 'Sotheby’s International Realty Uruguay',
    domain: 'sothebysrealty.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.sothebysrealty.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 6,
    trustLevel: 0.95,
    rateLimitPerMinute: 20,
    category: 'cadenas_inmobiliarias_uy',
    notes: 'Bienes raíces luxury costeros y urbanos',
  },
  {
    code: 'acs_uy',
    name: 'ACS Inmobiliaria',
    domain: 'acs.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.acs.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 7,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Operador tradicional en Montevideo',
  },
  {
    code: 'kosak_uy',
    name: 'Kosak Inversiones Inmobiliarias',
    domain: 'kosak.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.kosak.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 8,
    trustLevel: 0.9,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Inmobiliaria corporativa y residencial',
  },
  {
    code: 'meikle_uy',
    name: 'Meikle Bienes Raíces',
    domain: 'meikle.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.meikle.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 9,
    trustLevel: 0.95,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Especializado en Carrasco y franja este',
  },
  {
    code: 'caldeiro_uy',
    name: 'Caldeiro Victorica Bienes Raíces',
    domain: 'caldeyro.com',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.caldeyro.com',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 10,
    trustLevel: 0.9,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Operador inmobiliario corporativo y rural',
  },
  {
    code: 'pallares_bruzzone_uy',
    name: 'Pallares y Bruzzone',
    domain: 'pallaresbruzzone.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.pallaresbruzzone.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 11,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Inmobiliaria con foco en Montevideo norte y oeste',
  },
  {
    code: 'bado_asociados_uy',
    name: 'Bado y Asociados',
    domain: 'badoyasociados.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.badoyasociados.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 12,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Inmobiliaria residencial en Montevideo',
  },
  {
    code: 'braglia_uy',
    name: 'Braglia Inmobiliaria',
    domain: 'braglia.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.braglia.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 13,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Operador inmobiliario local',
  },
  {
    code: 'canepa_uy',
    name: 'Cánepa y Cánepa',
    domain: 'canepa.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.canepa.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 14,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Inmobiliaria tradicional uruguaya',
  },
  {
    code: 'nicolas_modena_uy',
    name: 'Nicolás de Módena Inmobiliaria',
    domain: 'nicolasdemodena.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.nicolasdemodena.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 15,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Operador residencial este y Maldonado',
  },
  {
    code: 'nieto_paez_uy',
    name: 'Nieto y Páez',
    domain: 'nietoypaez.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.nietoypaez.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 16,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Inmobiliaria montevideana',
  },
  {
    code: 'terramar_uy',
    name: 'Terramar Corporate & Residential',
    domain: 'terramar.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.terramar.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 17,
    trustLevel: 0.9,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Especializado en Punta del Este y Maldonado',
  },
  {
    code: 'puntamar_uy',
    name: 'Puntamar Real Estate',
    domain: 'puntamar.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.puntamar.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 18,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Inmobiliaria costera Maldonado / Rocha',
  },
  {
    code: 'century21_uy',
    name: 'Century 21 Uruguay',
    domain: 'century21.com.uy',
    countryCode: 'UY',
    sourceType: 'franquicia',
    baseUrl: 'https://www.century21.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 19,
    trustLevel: 0.95,
    rateLimitPerMinute: 40,
    category: 'cadenas_inmobiliarias_uy',
    notes: 'Franquicia internacional con presencia nacional',
  },
  {
    code: 'varela_uy',
    name: 'Varela Inmobiliaria',
    domain: 'varela.com.uy',
    countryCode: 'UY',
    sourceType: 'inmobiliaria',
    baseUrl: 'https://www.varela.com.uy',
    isActive: true,
    enabled: true,
    ingestionEnabled: false,
    priority: 20,
    trustLevel: 0.85,
    rateLimitPerMinute: 20,
    category: 'operadores_locales_uy',
    notes: 'Operador inmobiliario tradicional',
  },
];
