import { DocVariableDefinition, VariableCategory } from './types';

export const DOCUMENT_VARIABLES: DocVariableDefinition[] = [
  // --- 1. SOLICITANTE ---
  {
    key: 'applicant.full_name',
    label: 'Nombre completo del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.full_name',
    type: 'string',
    required: true,
    sourceLabel: 'Datos del solicitante',
    exampleValue: 'Ignacio Silva Gómez',
  },
  {
    key: 'applicant.first_name',
    label: 'Nombres del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.first_name',
    type: 'string',
    sourceLabel: 'Datos del solicitante',
    exampleValue: 'Ignacio',
  },
  {
    key: 'applicant.last_name',
    label: 'Apellidos del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.last_name',
    type: 'string',
    sourceLabel: 'Datos del solicitante',
    exampleValue: 'Silva Gómez',
  },
  {
    key: 'applicant.document_id',
    label: 'Cédula de Identidad / Documento',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.document_id',
    type: 'string',
    required: true,
    sourceLabel: 'Documento de Identidad',
    exampleValue: '4.182.930-1',
  },
  {
    key: 'applicant.email',
    label: 'Correo electrónico del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.email',
    type: 'string',
    required: true,
    sourceLabel: 'Datos de contacto',
    exampleValue: 'ignacio@ejemplo.com',
  },
  {
    key: 'applicant.phone',
    label: 'Teléfono celular del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.phone',
    type: 'string',
    required: true,
    sourceLabel: 'Datos de contacto',
    exampleValue: '099 123 456',
  },
  {
    key: 'applicant.address',
    label: 'Domicilio particular del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.address',
    type: 'string',
    sourceLabel: 'Declaración del solicitante',
    exampleValue: 'Benito Blanco 1245 Apto 402',
  },
  {
    key: 'applicant.department',
    label: 'Departamento de residencia',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.department',
    type: 'string',
    sourceLabel: 'Datos de residencia',
    exampleValue: 'Montevideo',
  },
  {
    key: 'applicant.marital_status',
    label: 'Estado civil del solicitante',
    category: 'solicitante',
    dataSource: 'borrowers',
    dataPath: 'applicant.marital_status',
    type: 'string',
    sourceLabel: 'Declaración jurada',
    exampleValue: 'Casado/a',
  },
  {
    key: 'applicant.occupation',
    label: 'Profesión u ocupación principal',
    category: 'solicitante',
    dataSource: 'borrower_income',
    dataPath: 'applicant.occupation',
    type: 'string',
    sourceLabel: 'Datos de ingresos',
    exampleValue: 'Ingeniero de Software / Dependiente',
  },
  {
    key: 'applicant.employer',
    label: 'Empleador o empresa de origen de ingresos',
    category: 'solicitante',
    dataSource: 'borrower_income',
    dataPath: 'applicant.employer',
    type: 'string',
    sourceLabel: 'Recibo de sueldo / Declaración',
    exampleValue: 'Tecnologías del Plata S.A.',
  },
  {
    key: 'applicant.monthly_income',
    label: 'Ingreso mensual líquido declarado',
    category: 'solicitante',
    dataSource: 'borrower_income',
    dataPath: 'applicant.monthly_income',
    type: 'currency',
    required: true,
    sourceLabel: 'Comprobante de ingresos / Recibo',
    exampleValue: '$ 95.000',
  },

  // --- 2. CÓNYUGE ---
  {
    key: 'spouse.full_name',
    label: 'Nombre completo del cónyuge / conviviente',
    category: 'conyuge',
    dataSource: 'borrowers',
    dataPath: 'spouse.full_name',
    type: 'string',
    sourceLabel: 'Declaración conyugal',
    exampleValue: 'María Elena Larrosa',
  },
  {
    key: 'spouse.document_id',
    label: 'Cédula de Identidad del cónyuge',
    category: 'conyuge',
    dataSource: 'borrowers',
    dataPath: 'spouse.document_id',
    type: 'string',
    sourceLabel: 'Documento cónyuge',
    exampleValue: '3.987.654-2',
  },

  // --- 3. PROPIEDAD EN GARANTÍA ---
  {
    key: 'property.padron',
    label: 'Padrón inmobiliario',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.padron',
    type: 'string',
    required: true,
    sourceLabel: 'Cédula Catastral / Declaración',
    exampleValue: '48.912',
  },
  {
    key: 'property.department',
    label: 'Departamento del inmueble',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.department',
    type: 'string',
    required: true,
    sourceLabel: 'Ficha de propiedad',
    exampleValue: 'Montevideo',
  },
  {
    key: 'property.city',
    label: 'Localidad / Ciudad del inmueble',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.city',
    type: 'string',
    sourceLabel: 'Ficha de propiedad',
    exampleValue: 'Montevideo',
  },
  {
    key: 'property.neighborhood',
    label: 'Barrio o zona del inmueble',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.neighborhood',
    type: 'string',
    sourceLabel: 'Ficha de propiedad',
    exampleValue: 'Pocitos',
  },
  {
    key: 'property.address',
    label: 'Dirección completa del inmueble',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.address',
    type: 'string',
    required: true,
    sourceLabel: 'Ficha de propiedad',
    exampleValue: 'Av. Brasil 2840',
  },
  {
    key: 'property.type',
    label: 'Tipo de inmueble (Casa, Apartamento, Local, etc.)',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.type',
    type: 'string',
    required: true,
    sourceLabel: 'Ficha de propiedad',
    exampleValue: 'Apartamento',
  },
  {
    key: 'property.area_m2',
    label: 'Superficie total en m²',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.area_m2',
    type: 'number',
    sourceLabel: 'Ficha catastral / Declaración',
    exampleValue: 120,
  },
  {
    key: 'property.estimated_value',
    label: 'Valor estimado declarado por solicitante',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.estimated_value',
    type: 'currency',
    required: true,
    sourceLabel: 'Declaración del solicitante',
    exampleValue: 'USD 180.000',
  },
  {
    key: 'property.appraised_value',
    label: 'Valor de tasación preliminar',
    category: 'propiedad',
    dataSource: 'property_valuations',
    dataPath: 'property.appraised_value',
    type: 'currency',
    sourceLabel: 'Valuación técnica / Informe',
    exampleValue: 'USD 185.000',
  },
  {
    key: 'property.legal_status',
    label: 'Situación jurídica del inmueble',
    category: 'propiedad',
    dataSource: 'properties',
    dataPath: 'property.legal_status',
    type: 'string',
    sourceLabel: 'Declaración jurídica',
    exampleValue: 'Libre de gravámenes',
  },

  // --- 4. CRÉDITO Y CONDICIONES ---
  {
    key: 'loan.requested_amount',
    label: 'Monto solicitado',
    category: 'credito',
    dataSource: 'applications',
    dataPath: 'loan.requested_amount',
    type: 'currency',
    required: true,
    sourceLabel: 'Solicitud del cliente',
    exampleValue: 'USD 60.000',
  },
  {
    key: 'loan.approved_amount',
    label: 'Monto aprobado u ofertado',
    category: 'credito',
    dataSource: 'lender_offers',
    dataPath: 'loan.approved_amount',
    type: 'currency',
    sourceLabel: 'Oferta de prestamista',
    exampleValue: 'USD 60.000',
  },
  {
    key: 'loan.currency',
    label: 'Moneda de la operación (USD / UYU)',
    category: 'credito',
    dataSource: 'applications',
    dataPath: 'loan.currency',
    type: 'string',
    required: true,
    sourceLabel: 'Solicitud',
    exampleValue: 'USD',
  },
  {
    key: 'loan.term_months',
    label: 'Plazo en meses',
    category: 'credito',
    dataSource: 'applications',
    dataPath: 'loan.term_months',
    type: 'number',
    required: true,
    sourceLabel: 'Condiciones pactadas',
    exampleValue: 36,
  },
  {
    key: 'loan.interest_rate',
    label: 'Tasa de interés anual (%)',
    category: 'credito',
    dataSource: 'lender_offers',
    dataPath: 'loan.interest_rate',
    type: 'percentage',
    sourceLabel: 'Propuesta crediticia',
    exampleValue: '11.50%',
  },
  {
    key: 'loan.monthly_payment',
    label: 'Cuota mensual estimada',
    category: 'credito',
    dataSource: 'calculated',
    dataPath: 'loan.monthly_payment',
    type: 'currency',
    sourceLabel: 'Cálculo paramétrico',
    exampleValue: 'USD 575',
  },
  {
    key: 'loan.ltv',
    label: 'Porcentaje financiado (LTV %)',
    category: 'credito',
    dataSource: 'calculated',
    dataPath: 'loan.ltv',
    type: 'percentage',
    sourceLabel: 'Cálculo de riesgo',
    exampleValue: '33.3%',
  },
  {
    key: 'loan.repayment_mode',
    label: 'Modalidad de amortización (Solo intereses / Amortizable)',
    category: 'credito',
    dataSource: 'applications',
    dataPath: 'loan.repayment_mode',
    type: 'string',
    sourceLabel: 'Condiciones de solicitud',
    exampleValue: 'Solo Intereses',
  },

  // --- 5. PRESTAMISTA ---
  {
    key: 'lender.name',
    label: 'Nombre / Razón Social del Prestamista',
    category: 'prestamista',
    dataSource: 'lenders',
    dataPath: 'lender.name',
    type: 'string',
    sourceLabel: 'Registro de acreedores',
    exampleValue: 'Fondo Inmobiliario del Este',
  },
  {
    key: 'lender.document_id',
    label: 'RUT o Documento del Prestamista',
    category: 'prestamista',
    dataSource: 'lenders',
    dataPath: 'lender.document_id',
    type: 'string',
    sourceLabel: 'Registro legal',
    exampleValue: '219876540018',
  },

  // --- 6. ESCRIBANO ---
  {
    key: 'notary.full_name',
    label: 'Nombre completo del escribano actuante',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.full_name',
    type: 'string',
    required: true,
    sourceLabel: 'Perfil profesional notarial',
    exampleValue: 'Esc. María Pérez Morales',
  },
  {
    key: 'notary.name',
    label: 'Nombre del escribano (alias)',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.name',
    type: 'string',
    sourceLabel: 'Perfil profesional',
    exampleValue: 'María Pérez',
  },
  {
    key: 'notary.document_number',
    label: 'Cédula de Identidad del Escribano',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.document_number',
    type: 'string',
    sourceLabel: 'Documento notarial',
    exampleValue: '3.892.415-8',
  },
  {
    key: 'notary.notarial_fund_affiliate_number',
    label: 'N.º de afiliado a Caja Notarial',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.notarial_fund_affiliate_number',
    type: 'string',
    required: true,
    sourceLabel: 'Caja Notarial de Seguridad Social',
    exampleValue: '48.291',
  },
  {
    key: 'notary.professional_address',
    label: 'Domicilio profesional del escribano',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.professional_address',
    type: 'string',
    required: true,
    sourceLabel: 'Estudio notarial',
    exampleValue: 'Rincón 487 Piso 3 Esc. 302',
  },
  {
    key: 'notary.professional_city',
    label: 'Ciudad / Localidad profesional',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.professional_city',
    type: 'string',
    sourceLabel: 'Estudio notarial',
    exampleValue: 'Montevideo',
  },
  {
    key: 'notary.professional_department',
    label: 'Departamento profesional',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.professional_department',
    type: 'string',
    sourceLabel: 'Estudio notarial',
    exampleValue: 'Montevideo',
  },
  {
    key: 'notary.electronic_domicile',
    label: 'Domicilio electrónico oficial del escribano',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.electronic_domicile',
    type: 'string',
    sourceLabel: 'Registro electrónico SCJ',
    exampleValue: 'maria.perez@notarios.org.uy',
  },
  {
    key: 'notary.notary_office_name',
    label: 'Nombre del Estudio Notarial',
    category: 'escribano',
    dataSource: 'notary_offices',
    dataPath: 'notary.notary_office_name',
    type: 'string',
    sourceLabel: 'Estudio Notarial',
    exampleValue: 'Estudio Fernández & Asociados',
  },
  {
    key: 'notary.digital_certificate_identifier',
    label: 'Identificador del Certificado de Firma Digital',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.digital_certificate_identifier',
    type: 'string',
    sourceLabel: 'Firma Digital Avanzada',
    exampleValue: 'UY-CA-ABITAB-48291-MP',
  },
  {
    key: 'notary.email',
    label: 'Email del escribano',
    category: 'escribano',
    dataSource: 'notary_profiles',
    dataPath: 'notary.email',
    type: 'string',
    sourceLabel: 'Contacto profesional',
    exampleValue: 'escribania@estudiofernandez.uy',
  },

  // --- 7. EXPEDIENTE ---
  {
    key: 'case.code',
    label: 'Código público del expediente',
    category: 'expediente',
    dataSource: 'applications',
    dataPath: 'case.code',
    type: 'string',
    required: true,
    sourceLabel: 'Identificador oficial HPT',
    exampleValue: 'HPT-2026-00124',
  },
  {
    key: 'case.created_at',
    label: 'Fecha de ingreso de solicitud',
    category: 'expediente',
    dataSource: 'applications',
    dataPath: 'case.created_at',
    type: 'date',
    sourceLabel: 'Registro inicial',
    exampleValue: '04/09/2026',
  },
  {
    key: 'case.days_open',
    label: 'Días de tramitación activa',
    category: 'expediente',
    dataSource: 'calculated',
    dataPath: 'case.days_open',
    type: 'number',
    sourceLabel: 'Cálculo de expediente',
    exampleValue: 3,
  },

  // --- 8. FECHAS ---
  {
    key: 'dates.today_formatted',
    label: 'Fecha actual formateada',
    category: 'fechas',
    dataSource: 'system',
    dataPath: 'dates.today_formatted',
    type: 'string',
    sourceLabel: 'Sistema',
    exampleValue: '4 de septiembre de 2026',
  },

  // --- 9. DATOS DEL TENANT / INSTITUCIÓN ---
  {
    key: 'tenant.name',
    label: 'Nombre comercial del Tenant',
    category: 'tenant',
    dataSource: 'organizations',
    dataPath: 'tenant.name',
    type: 'string',
    required: true,
    sourceLabel: 'Configuración de Tenant',
    exampleValue: 'HIPOTECALY Uruguay',
  },
  {
    key: 'tenant.legal_name',
    label: 'Razón social del Tenant',
    category: 'tenant',
    dataSource: 'tenant_docflow_settings',
    dataPath: 'tenant.legal_name',
    type: 'string',
    sourceLabel: 'Configuración Legal',
    exampleValue: 'HIPOTECALY S.A.S.',
  },
  {
    key: 'tenant.legal_representative',
    label: 'Representante legal del Tenant',
    category: 'tenant',
    dataSource: 'tenant_docflow_settings',
    dataPath: 'tenant.legal_representative',
    type: 'string',
    sourceLabel: 'Configuración Legal',
    exampleValue: 'Dr. Alejandro Méndez',
  },
];

export const VARIABLE_CATEGORIES: Array<{
  id: VariableCategory;
  label: string;
  description: string;
}> = [
  { id: 'solicitante', label: 'Solicitante', description: 'Datos personales, contacto y ocupación del titular' },
  { id: 'conyuge', label: 'Cónyuge / Conviviente', description: 'Datos del cónyuge o garante conyugal' },
  { id: 'propiedad', label: 'Propiedad en Garantía', description: 'Padrón, dirección, superficies y valuación' },
  { id: 'credito', label: 'Crédito y Condiciones', description: 'Montos, plazo, tasa, LTV y cuota mensual' },
  { id: 'prestamista', label: 'Prestamista / Acreedor', description: 'Datos de la entidad o persona que financia' },
  { id: 'escribano', label: 'Escribano Actuante', description: 'Datos del profesional notarial asignado' },
  { id: 'inmobiliaria', label: 'Inmobiliaria / Broker', description: 'Intermediario comercial o estudio' },
  { id: 'expediente', label: 'Expediente', description: 'Código público HPT, fechas y estado operativo' },
  { id: 'fechas', label: 'Fechas y Sistema', description: 'Fechas de emisión y cómputos temporales' },
  { id: 'tenant', label: 'Institución / Tenant', description: 'Branding, razón social y representante' },
];

/**
 * Obtiene el valor anidado a partir de una ruta como "applicant.full_name"
 */
export function getNestedValue(obj: Record<string, any>, path: string): any {
  if (!obj || !path) return undefined;
  const parts = path.split('.');
  let current: any = obj;
  for (const part of parts) {
    if (current === undefined || current === null) return undefined;
    current = current[part];
  }
  return current;
}
